name: ✏️ Verify formatting

on:
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  format-check:
    name: Verify formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          Equinor.ProCoSys.Preservation.Command,
          Equinor.ProCoSys.Preservation.Domain,
          Equinor.ProCoSys.Preservation.Infrastructure,
          Equinor.ProCoSys.Preservation.MainApi,
          Equinor.ProCoSys.Preservation.MessageContracts,
          Equinor.ProCoSys.Preservation.Query,
          Equinor.ProCoSys.Preservation.WebApi,
          tests/Equinor.ProCoSys.Preservation.Command.Tests,
          tests/Equinor.ProCoSys.Preservation.Domain.Tests,
          tests/Equinor.ProCoSys.Preservation.Infrastructure.Tests,
          tests/Equinor.ProCoSys.Preservation.MainApi.Tests,
          tests/Equinor.ProCoSys.Preservation.Query.Tests,
          tests/Equinor.ProCoSys.Preservation.Test.Common,
          tests/Equinor.ProCoSys.Preservation.WebApi.IntegrationTests,
          tests/Equinor.ProCoSys.Preservation.WebApi.Tests,
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ vars.EQUINOR_PROCOSYS_NON_PROD_DEVOPS_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Get DevOps Token
        id: 'get-devops-token'
        uses: ./.github/actions/get-devops-token
      
      - name: Configure Nuget
        uses: ./.github/actions/nuget-config
        with:
          access-token: ${{ steps.get-devops-token.outputs.token }}

      - name: Verify ${{ matrix.project }} formatting
        run: |
          dotnet format ./src/${{ matrix.project }} --verify-no-changes
